cache_dir: "/Volumes/Dock/Ansible Cache"
java_dir: "/Library/Java/JavaVirtualMachines"
java_os: mac
java_arch: aarch64
java_env_toplevel: /Contents/Home
env_script_dir: /Volumes/Dock/DevTools/Scripts

