proxmox_hosts:
  hosts:
    omega:
      ansible_host: 10.1.1.8
proxmox_hosted:
  children:
    proxmox_vms:
      hosts:
    proxmox_lxc:
      hosts:
        filer:
        auth:
        db:
        git:
development:
  hosts:
    alpha:
    rho:
    rho-win11:
      ansible_connection: winrm
      ansible_host: rho
      ansible_port: 59850
      ansible_winrm_scheme: http
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
    mu:
    pi:
    epsilon:
ungrouped:
  hosts:
    power:

