- name: Create directory for icons
  ansible.builtin.file:
    path: "{{ env_linux_icon_dir }}"
    mode: '0755'
    state: directory

- name: Copy {{ env_name }} environment script icon
  ansible.builtin.copy:
    src: "{{ env_icon_file }}"
    dest: "{{ env_linux_icon_dir }}/{{ env_icon }}.svg"
    owner: root
    group: root
    mode: '0644'

- name: Create directory for Konsole profiles
  ansible.builtin.file:
    path: "{{ env_linux_konsole_dir }}"
    mode: '0755'
    state: directory

- name: Copy {{ env_name }} environment Konsole profile
  ansible.builtin.template:
    src: konsole.profile.j2
    dest: "{{ env_linux_konsole_dir }}/{{ env_name }}.profile"
    owner: root
    group: root
    mode: '0644'

